### ISSUE TITLE
Data-processing problem

### ISSUE THREAD

**Issue by geraltofrivia** [nusnlp/namanda#1]
Hello, 

In file `https://github.com/nusnlp/namanda/blob/master/NAMANDA/scripts/prepend_nil.py`, around line 22 there's a block which looks for `all_answers` in the `dev_nil.json` file. 

However, after following the steps mentioned in `prep-data` dir, I couldn't find that key (`all_answers`) anywhere in the JSON file. Is that an expected behaviour? 

I ask because if I ignore that code block, and move ahead, the number of training features are reported as 0, during training.

**Comment by sk210892** [comment]
Should work now. It was a typo!
